# Generated by Django 2.0.4 on 2018-04-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('customerName', models.CharField(blank=True, max_length=100)),
                ('totTax', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('totDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('invoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Item_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('unitsAdded', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('priceperunit', models.IntegerField()),
                ('isMultipliable', models.BooleanField(default=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='item_history',
            name='itemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Items'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='itemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Items'),
        ),
    ]
