# Generated by Django 2.0.4 on 2018-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180430_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='oneUnitQuantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
