# Generated by Django 2.0.4 on 2018-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_items_oneunitquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='unitsAvailable',
            field=models.IntegerField(default=0),
        ),
    ]
