# Generated by Django 2.0.4 on 2018-04-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_items_unitsavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='quantity',
            new_name='noOfUnits',
        ),
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.CharField(default='g', max_length=10),
        ),
    ]
