# Generated by Django 2.0.4 on 2018-04-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180430_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='totDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totTax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
