# Generated by Django 2.0.4 on 2018-04-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180430_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='price',
        ),
    ]
