# Generated by Django 2.0.4 on 2018-04-30 21:21

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('api', '0009_auto_20180430_2120'),
    ]
    atomic=False
    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetail',
            new_name='InvoiceDetails',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
atomic=False