# Generated by Django 2.0.4 on 2018-04-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180430_2121'),
    ]
    atomic=False
    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
