# Generated by Django 2.0.4 on 2018-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_invoice_mobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='totAmt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customerName',
            field=models.CharField(max_length=100),
        ),
    ]
