# Generated by Django 2.0.4 on 2018-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='m@g.com', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
