# Generated by Django 2.0.4 on 2018-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authToken',
            field=models.CharField(default='ec763eb4bd7441ebaf9db6611935cf96', max_length=50),
        ),
    ]
